### ISSUE TITLE
RNG cap based on average damage

### ISSUE THREAD

**Issue by cmavelis** [Groove-of-War/project-groove#3]
cap to +-10% of the avg damage to be dealt

e.g. 10%HP damage will have a range of +/- 1%

This will require editing combat.lua

**Comment by cmavelis** [comment]
![image](https://user-images.githubusercontent.com/16199008/84510469-2807ef00-ac93-11ea-87f1-514e699de308.png)

**Comment by cmavelis** [comment]
![image](https://user-images.githubusercontent.com/16199008/84814288-3fbadc80-afdf-11ea-82b8-8e37a50654fd.png)
should this be the result? the median here is 27, so should the +/- round before or after applying it to the median dmg? @GimbleB ?

**Comment by cmavelis** [comment]
I think it's good, and easier to understand, as long as it's consistently rounding before

**Comment by FlySniper** [comment]
Ahh yes. The rounding is caused by floating point issues. Here's a picture of rounding those numbers in python:
![image](https://user-images.githubusercontent.com/2828257/84816115-020b8300-afe2-11ea-83a7-d57e6b6e544d.png)

**Comment by GimbleB** [comment]
It looks like the first number is correct, the counterattack damage seems to be slightly off though.

**Comment by cmavelis** [comment]
I don't know if that's what's going on here, since combat.lua uses math.floor across the board

**Comment by FlySniper** [comment]
The counter attack damage should have more variance since the counterattack could take place where Valder has anywhere between 76HP and 70HP. And then once the attack is done, the counterattack has RNG with it.

To be sure, I did some testing with the mod on and off for the scenario above, except on roads instead of plains.  With both the mod on and off the result was the same, except the high roll was 48 instead of 49. This can be overlooked due to the aforementioned floating point errors

**Comment by GimbleB** [comment]
Right, that makes sense.

**Comment by cmavelis** [comment]
Ah I forgot about that fact with the counterattack, good point

However, am I correct to think floating point error wouldn't be an issue, since it's math.floor() not math.round() here?

**Comment by FlySniper** [comment]
Floating point issues affect rounding. Plus the math.floor is being used like a math.round. 
math.floor(x + 0.5) == math.round(x)

**Comment by cmavelis** [comment]
Regardless, we can print the extra decimals to check if that's the case here, since it's not apparent it would be rounding an x.5 here, which is the only time it would affect

**Comment by FlySniper** [comment]
That may not help either??? But the RNG difference between the two combat.lua algorithms is so minor, I'm ok with leaving it be.  If we run into issues with desyncs, then we can revisit the algorithm.

**Comment by cmavelis** [comment]
I'm not worried about desyncs, but I do want to be able to speak to what's going on here.  I was posting this to verify this is what we expect, since I think it is correct.  
0.1*27 = 2.7
27 - 2.7 = 24.3
27 + 2.7 = 29.7
Correct rounding makes this 24-30

**Comment by FlySniper** [comment]
Oh I see what you're saying, my mind went on a different track. Don't mind me then
